export const FETCH_STATIONS = 'FETCH_STATION'
export const FETCH_STATIONS_SUCCESS = 'FETCH_STATION_SUCCESS'
export const FETCH_STATIONS_ERROR = 'FETCH_STATION_ERROR'

export const FETCH_WINDDIR = 'FETCH_WINDDIR'
export const FETCH_WINDDIR_SUCCESS = 'FETCH_WINDDIR_SUCCESS'
export const FETCH_WINDDIR_ERROR = 'FETCH_WINDDIR_ERROR'

export const FETCH_WINDLEVEL = 'FETCH_WINDLEVEL'
export const FETCH_WINDLEVEL_SUCCESS = 'FETCH_WINDLEVEL_SUCCESS'
export const FETCH_WINDLEVEL_ERROR = 'FETCH_WINDLEVEL_ERROR'

export const FETCH_RAIN = 'FETCH_RAIN'
export const FETCH_RAIN_SUCCESS = 'FETCH_RAIN_SUCCESS'
export const FETCH_RAIN_ERROR = 'FETCH_RAIN_ERROR'

export const FETCH_WATER = 'FETCH_WATER'
export const FETCH_WATER_SUCCESS = 'FETCH_WATER_SUCCESS'
export const FETCH_WATER_ERROR = 'FETCH_WATER_ERROR'

export const FETCHING = 'FETCHING'
export const SUCCESS = 'success'

export const WINDDIR = 'winddir'
